### PR TITLE
Workaround for pagination bug

### PR DESCRIPTION
**Pull request by mininao**
Since pagination doesn't work anymore, i think a dirty workaround like this is the best thing to do until somebody more competent than me is able to fix the thing.  
(Setting pagination limit to 9999999 instead of 20)  
Of course, this will have to be reverted once the right fixes are made

### CODE REVIEW

**Comment by gterrono** [comment]
Good idea!

I think this is a solid temporary solution. How about you @AlexeyMK?

**Comment by AlexeyMK** [comment]
I haven't looked at the pagination code, really. So if you're comfortable
with it, let's :shipit:

**Comment by mininao** [comment]
Any updates on this issue guys ;) ?

**Comment by AlexeyMK** [comment]
@gterrono, do you mind grabbing this? I haven't dug into this code and I am short on bandwidth for the next several weeks.  If the solution is simply to merge this PR let me know and I will.

**Comment by gterrono** [comment]
Sorry for the delay!

I've been trying to test this and get a better solution working, but I can't get any test app working for some reason. @AlexeyMK can you just see that it works well for the 1000 item collection and merge it if it all seems good?

**Comment by gterrono** [comment]
I found the bug, by the way. It's [here](https://github.com/gterrono/houston/blob/master/client/collection_view.coffee#L72).

We need to pass the collection name into `collection_count()`. I think it should be somewhere on `this`, but I couldn't get it to log or a debugger to work for some reason.

**Comment by AlexeyMK** [comment]
I ended up resolving this in v2.0.3 (in a slightly cleaner way - you can set a configuration setting instead of hardcoding)

**Comment by mininao** [comment]
Thanks a lot guys !

**Pull request closed without merging**
