### PR TITLE
Fixed the leak

### PR DESCRIPTION
**Pull request by gterrono**
It's working well. There's some somewhat hacky things I had to do because we need to know if an admin exists on the frontend. Also because of the way publishing is handled we need to refresh the page after creating a user and then making them admin.

### CODE REVIEW

**Comment by AlexeyMK** [comment]
Generally looks good. How do you feel about not publishing admins but
exposing a method ie, adminExists, and checking currentUserIsAdmin via
either a method or just making the publication of Houston data conditional
on that?

**Comment by gterrono** [comment]
Yeah, that was my original plan. It's pretty difficult though, because the whole ui relies on that, so we'd need to delay the router rendering anything until we hear back from the two methods.

**Comment by gterrono** [comment]
Making the publication conditional on the current user being admin is what I did, right?

**Comment by AlexeyMK** [comment]
Overloading the admins collection to insert `{exists: true}` feels dirty, but is probably not the worst thing. I don't have an obviously better solution that doesn't delay router rendering, though. FWIW, router rendering is already delayed by needing a logged in user, no?

**Comment by AlexeyMK** [comment]
I think this is :ship: able-though.

**Comment by gterrono** [comment]
Yeah, that direction seemed a bit more complicated, but it might be better in the end. It's good enough for now though.

**Pull request merged**
